apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: mario
          image: kaminskypavel/mario
          ports:
          - name: mario
            containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mario-service
  labels:
    app: my-app
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: my-app
  type: ClusterIP
